"""Flatten `fixture_ukf_reference.json` into a CSV for the Kotlin harness.

Why this exists rather than parsing the JSON from Kotlin: the parity gate has to run
with `kotlinc` and nothing else. No Gradle, no artifact resolution, no network. That
keeps the gate runnable by anyone in seconds, on any machine, which is the only
reason a gate actually gets run. Hand-rolling a JSON parser in Kotlin just to read a
test fixture would be adding a second thing that can be subtly wrong to a tool whose
whole job is catching things that are subtly wrong.

The CSV is derived, never committed and never edited. `fixture_ukf_reference.json`
stays the single source of truth; this file is a projection of it. If the two ever
disagree, the JSON wins.

Run:
    python -m tools.parity.export_fixture_csv --output /tmp/fixture.csv
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

_DEFAULT_FIXTURE = Path(__file__).resolve().parent / "fixture_ukf_reference.json"

_COLUMNS = [
    "i",
    "t_s",
    "dt_s",
    "gyro_yaw_rps",
    "gnss_available",
    "gnss_n",
    "gnss_e",
    "exp_pn",
    "exp_pe",
    "exp_vn",
    "exp_ve",
    "exp_psi",
]


def export(fixture: dict) -> str:
    initial = fixture["initial_state"]
    tolerances = fixture["tolerances"]

    lines = [
        "# generated by tools/parity/export_fixture_csv.py, do not commit or edit",
        f"# source={fixture['reference_implementation']}",
        f"# n_cycles={fixture['n_cycles']}",
        f"# init_pos_n={initial['pos_m'][0]!r}",
        f"# init_pos_e={initial['pos_m'][1]!r}",
        f"# init_vel_n={initial['vel_mps'][0]!r}",
        f"# init_vel_e={initial['vel_mps'][1]!r}",
        f"# init_heading={initial['heading_rad']!r}",
        f"# tol_position_m={tolerances['position_m']!r}",
        f"# tol_velocity_mps={tolerances['velocity_mps']!r}",
        f"# tol_heading_rad={tolerances['heading_rad']!r}",
        ",".join(_COLUMNS),
    ]

    for cycle in fixture["cycles"]:
        step_input = cycle["input"]
        expected = cycle["expected"]
        available = bool(step_input["gnss_available"])
        # A blackout cycle has no GNSS position at all. NaN rather than 0, so a
        # harness that ignores the availability flag fails loudly instead of
        # quietly steering the filter to the origin.
        gnss = step_input["gnss_pos_m"] if available else [float("nan"), float("nan")]

        lines.append(
            ",".join(
                repr(value) if isinstance(value, float) else str(value)
                for value in [
                    cycle["i"],
                    cycle["t_s"],
                    step_input["dt_s"],
                    step_input["gyro_yaw_rps"],
                    1 if available else 0,
                    gnss[0],
                    gnss[1],
                    expected["pos_m"][0],
                    expected["pos_m"][1],
                    expected["vel_mps"][0],
                    expected["vel_mps"][1],
                    expected["heading_rad"],
                ]
            )
        )

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixture", default=str(_DEFAULT_FIXTURE))
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    fixture = json.loads(Path(args.fixture).read_text())
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(export(fixture), encoding="utf-8")
    print(f"Wrote {output} ({fixture['n_cycles']} cycles)")


if __name__ == "__main__":
    main()
